apiVersion: v1
kind: Service
metadata:
  name: "authserver-service"
spec:
  selector:
    app: authserver
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authserver
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1  
  template:
    metadata:
      labels:
        app: authserver
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: authserver
        image: z33p/one-study:authserver_1.0.0
        ports:
        - containerPort: 80

