apiVersion: v1
kind: Service
metadata:
  name: "neptune-service"
spec:
  selector:
    app: neptune
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neptune
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1  
  template:
    metadata:
      labels:
        app: neptune
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: neptune
        image: z33p/one-study:neptune_1.0.0
        ports:
        - containerPort: 80

