# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
    paths:
      - 'sun/**'
      - '.github/workflows/nodejs.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'sun/**'
      - '.github/workflows/nodejs.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: instaling dependencies
      working-directory: 'sun'
      run: yarn install --frozen-lockfile
      
    - name: building
      working-directory: 'sun'
      run: yarn build --if-present
      
    - name: testing
      working-directory: 'sun'
      run: yarn test
      

